# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161207_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(upload_to='/Users/type3/Projects/michael_brooks/brooks/settings/../../media'),
        ),
    ]
